//
// Created by Surge Raval on 3/30/18.
//
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class projekt_substratum_compiler_aapt_Aapt */

#ifndef _Included_projekt_substratum_compiler_aapt_Aapt
#define _Included_projekt_substratum_compiler_aapt_Aapt
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     projekt_substratum_compiler_aapt_Aapt
 * Method:    JNImain
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_projekt_substratum_compiler_aapt_Aapt_JNImain
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif


